//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AddId { get; set; }
        public System.DateTime AdDatePublication { get; set; }
        public Nullable<int> Userid { get; set; }
        public string AdTitle { get; set; }
        public Nullable<int> Statuid { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<decimal> AdPrice { get; set; }
        public Nullable<int> CityId { get; set; }
        public string AdDescription { get; set; }
        public string Photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Types Types { get; set; }
        public virtual Users Users { get; set; }
    }
}
